### ISSUE TITLE
Unable to add to new Statamic install

### ISSUE THREAD

**Issue by tnorthcutt** [statamic/preset-tailwindcss#1]
I just set up a brand new local Statamic install and tried to add this preset, and got this error message: 

```
[InvalidArgumentException]
Could not find a version of package statamic/preset-tailwindcss matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

I'm confident I can work out how to resolve this (though I'm happy to hear a suggestion), but it's not a great first-run experience so I figured I'd report it 😄

Steps to reproduce:
- `composer global require statamic/cli`
- `statamic new sitename`
- `cd sitename`
- `composer require statamic/preset-tailwindcss`

**Comment by jasonvarga** [comment]
This is for Statamic v3.

**Comment by tnorthcutt** [comment]
@jasonvarga Right, I saw that. I'm guessing by you closing this, that means current Statamic (`statamic new`) isn't v3.x... but that wasn't obvious at first 😄

**Comment by jasonvarga** [comment]
I'm glad this repo was so easily discoverable, which is what we want when v3 is out. But, it isn't, yet. Sorry for the confusion!

**Comment by jackmcdade** [comment]
This is for v3 :) not out yet.

**Comment by tnorthcutt** [comment]
👍 I'm new to Statamic, so still figuring out context/overall lay of the land. Probably a non-issue to folks familiar with stuff. Cheers!
